### ISSUE TITLE
Interaction error

### ISSUE THREAD

**Issue by T0miiis** [Elitex07/GiveawayBot#11]
Hi, how can i fix that?

![image](https://user-images.githubusercontent.com/105943665/219731745-33f08bb3-7816-40e5-8ca1-113b8fde3afc.png)
![image](https://user-images.githubusercontent.com/105943665/219731923-459967f5-2036-43f8-b753-a10aef927abd.png)

**Comment by Elitex07** [comment]
@T0miiis Are you sure that your handler is supporting the way the command being executed? 

Additionally, "The reply to this interaction has not been sent or deferred." comes when you try to edit a response of Interaction, without actually making the response.

**Comment by Elitex07** [comment]
Fixed thru Discord Server Support
