### ISSUE TITLE
No winners registered in the db

### ISSUE THREAD

**Issue by UnschooledGamer** [Elitex07/GiveawayBot#12]
when a giveaway passes it's **endTime** while the bot is offline then as it restarts the bot shows the winner but doesn't save it in database because of this code
`i.winners.push(rid);` at [keepGawAlive.js#L88](https://github.com/Elitex07/GiveawayBot/blob/main/src/events/services/keepGawAlive.js#L88)

**if you want to fix you can then too, I'm going create pr later on.**

**Comment by UnschooledGamer** [comment]
I hope this case is not in Raiden's code.

**Comment by Elitex07** [comment]
Damn, I forgot to push changes. Now commits are ahead. I'll fix them till tmr.

**Comment by Elitex07** [comment]
Can yu explain ?

**Comment by Elitex07** [comment]
I hope this [commit](https://github.com/Elitex07/GiveawayBot/commit/ef3dbc723b9aa49efb10d04c1a601e9d78d50a81) fixes it.

Thanks :)
