### ISSUE TITLE
Entries at Giveaway Ends

### ISSUE THREAD

**Issue by Ashlovecode** [Elitex07/GiveawayBot#5]
**How can I make the button disabled after ending the Ending the gaw despite of removal**
When giveaway ends, bot removes the button, and we are left with no idea of, how many entries were actually taken, How can I make the bot to do so..

**Comment by Elitex07** [comment]
Hey,

This can be done by modifying the Giveaway ending code. Giveaway ending code is in `src/events/keepGawAlive.js` and `src/slashCommands/Utility/giveaway.js`.

If done properly, bot will not break. It is a customizable repo
